version: 2.1

defaults:
- &save_dependencies_cache
  save_cache:
    paths:
    - ~/.ivy2
    - ~/.sbt
    key: dependencies-{{ .Branch }}-{{ checksum "build.sbt" }}
- &restore_dependencies_cache
  restore_cache:
    keys:
    - dependencies-{{ .Branch }}-{{ checksum "build.sbt" }}
    - dependencies-{{ .Branch }}
    - dependencies

- &configure_git_credetials
  run:
    name: Configure git credentials
    command: |
      echo 'Adding the github host SSH key...'
      mkdir -p -m 0700 ~/.ssh/
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git config user.name ovo-comms-circleci
      git config user.email "hello.comms@ovoenergy.com"


executors:
  docker:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      JAVA_OPTS: "-Xmx1g -XX:MaxMetaspaceSize=1g -XX:MetaspaceSize=1g -XX:+CMSClassUnloadingEnabled"
      AWS_REGION: "eu-west-1"
      AWS_DEFAULT_REGION: "eu-west-1"
      TEST_TIME_SCALE_FACTOR: 3
  machine:
    machine:
      enabled: true
    environment:
      JAVA_OPTS: "-Xmx1g -XX:MaxMetaspaceSize=1g -XX:MetaspaceSize=1g -XX:+CMSClassUnloadingEnabled"
      AWS_REGION: "eu-west-1"
      AWS_DEFAULT_REGION: "eu-west-1"
      TEST_TIME_SCALE_FACTOR: 3

jobs:
  build:

    executor: docker

    steps:

    - checkout

    - *restore_dependencies_cache

    - run: sbt update

    - *save_dependencies_cache

    - run:
        name: Scalafmt Check
        command: sbt scalafmtCheck test:scalafmtCheck

    - run:
        name: Compile
        command: sbt test:compile

    - persist_to_workspace:
        root: .
        paths: # TODO is there a better way to do this? So that the publish step doesn't have to recompile everything.
        - target
        - project/target
        - project/project/target
        - core/target
        - clients/target

  test:

    executor: machine

    steps:

    - checkout

    - attach_workspace:
        at: .

    - *restore_dependencies_cache

    - run:
        name: Test
        command: sbt test:test

    - store_test_results:
        path: target/test-reports

    - store_artifacts:
        path: target/gc.log

  integration_test:

    executor: docker

    steps:

    - checkout

    - attach_workspace:
        at: .

    - *restore_dependencies_cache

    - run:
        name: Test
        command: sbt it:test

    - store_test_results:
        path: target/test-reports

  publish:

    executor: docker

    steps:
    - checkout

    - attach_workspace:
        at: .

    - *restore_dependencies_cache

    - *configure_git_credetials

    - run:
        name: Tag Release
        command: build/tag.sh

    - run:
        name: Release
        command: sbt releaseEarly

workflows:
  build-and-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
    - integration_test:
        requires:
        - build
    - publish:
        requires:
        - build
        - test
        - integration_test
        filters:
          branches:
            only:
            - master
