name: ci

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/heads/release/' ) }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - uses: coursier/cache-action@v6
      - run: sbt update
      - uses: scalacenter/sbt-dependency-submission@v2
        if: github.ref == 'refs/heads/main'

  build:
    runs-on: ubuntu-latest
    needs: update-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - run: sbt "+scalafmtCheckAll;+headerCheckAll;+compile;+Test/compile;IntegrationTest/compile;scalafixAll --check"
      - uses: alehechka/upload-tartifact@v2
        with:
          name: targets
          path: "**/target/**"
          if-no-files-found: error
          retention-days: 1

  snyk:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: SET UP - Snyk
        uses: snyk/actions/scala@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high --fail-on=all

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - uses: alehechka/download-tartifact@v2
        with:
          name: targets
          path: .
      - run: sbt "+Test/test"
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: unit tests report
          path: target/test-reports/*.xml
          reporter: java-junit
      - uses: actions/upload-artifact@v3
        with:
          name: unit-test.log
          path: target/unit-test.log

  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    services:
      dynamodb:
        image: amazon/dynamodb-local:1.21.0
        ports:
          - "8000:8000"

    env:
      DYNAMODB_ENDPOINT: "http://localhost:8000"
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - uses: alehechka/download-tartifact@v2
        with:
          name: targets
          path: .
      - run: sbt +IntegrationTest/test
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          list-suites: "all"
          list-tests: "all"
          max-annotations: 10
          fail-on-error: true
          name: integration tests report
          path: target/it-reports/*.xml
          reporter: java-junit
      - uses: actions/upload-artifact@v2
        with:
          name: integration-test.log
          path: target/integration-test.log

  publish:
    if: github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/heads/release/' ) # Only runs on releases
    runs-on: ubuntu-latest
    needs:
      - unit-tests
      - integration-tests
      - snyk
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - uses: coursier/cache-action@v6
      - uses: alehechka/download-tartifact@v2
        with:
          name: targets
          path: .
      - run: git fetch --tags
      - run: git status
      - name: Bump version and push tag
        id: tag-version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          TAG_CONTEXT: branch
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag-version.outputs.new_tag }}
          name: ${{ steps.tag-version.outputs.new_version }}
          body: ${{ steps.tag-version.outputs.changelog }}
      - run: git fetch --tags
      - name: publish
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}
        run: sbt +publish
