on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

name: Scala Steward
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: scala-steward-org/scala-steward-action@v2
        with:
          branches: main
          github-app-id: ${{ vars.SCALA_STEWARD_APP_ID }}
          github-app-installation-id: ${{ vars.SCALA_STEWARD_APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.SCALA_STEWARD_APP_PRIVATE_KEY }}
          other-args: "--add-labels"
